# src/main/resources/application.yml
server:
  port: 9103

spring:
  application:
    name: knowledge-planet-order
  profiles:
    active: local # Keep your active profile

  # --- Database Configuration (USING SHARDINGSPHERE) ---
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # URL points to the ShardingSphere configuration file on the classpath
    url: jdbc:shardingsphere:classpath:shardingsphere-order-${spring.profiles.active}.yaml
    # Username/Password are defined within the shardingsphere YAML file per datasource

  # --- Mybatis Plus Configuration ---
  mybatis-plus:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.example.common.entity, com.example.order.entity # Include local entities if any
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        # *** IMPORTANT: Use ASSIGN_ID for Snowflake ID generation by MybatisPlus ***
        # This works well with ShardingSphere when sharding by 'id'
        id-type: assign_id
        # logic-delete configuration if needed
  redis:
    host: localhost
    port: 6379
  # --- Spring Cloud Stream & RocketMQ Configuration (Producer - Keep as before) ---

  cloud:
    stream:
      default-binder: rocketmq                # 建议统一指定
      binders:
        rocketmq:
          type: rocketmq
          environment:
            spring:
              cloud:
                stream:
                  rocketmq:
                    binder:
                      name-server: 127.0.0.1:9876

      bindings:                               # 通道的通用属性（与具体 binder 无关）
        paymentSuccessOutput-out-0:
          destination: payment-success-topic
          content-type: application/json

      rocketmq:                               # ★ binder 专属配置（Producer / Consumer 组等）
        bindings:
          paymentSuccessOutput-out-0:         # 与上面 bindings 的 key 完全一致
            producer:
              group: order-service-producer-group

# --- Knife4j Swagger Configuration (Keep as before) ---
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'order-service'
      paths-to-match: '/**'
      packages-to-scan: com.example.order.controller

# --- Custom Application Properties (Keep as before) ---
app:
  message-relay:
    enabled: true
    fixed-delay: 10000
    batch-size: 50

# --- Alipay Configuration ---
alipay:
  app-id: 9021000134628973
  merchant-private-key: "MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCOS28T1EpfBQmSW4y/9TNWbD1jPgQiA7NUBbp3+atkBRYRHROWAuDleYNfUu3pREnoMV60leTvxowNBVIKj8uAgk4nBplhU0EegGOF2HRI0Q5maMm5ufbrfyGgnxcOb3CBUJUzfJt60ueeoUL4l56lvQV91MdqbFHEe6yOcTT3FmUFm3FQ9iFS2Nt+iHEW7grYKU1y/mehNszowBSzWhiTV03Jn9PnXjRACV3PvMJ0RhpQzrZ+8LsRlfQPsp3xwDFwx49u95Q8JlQlr3TzUbtE4EmPCUWMQSwmdlR7yiCNqvMLp4Y0sVtQKVnKvPLlP2UbVduMwY6pdeBy5bKr4yTnAgMBAAECggEABNOcNfD6gNSb6YH/eTdpAWJ0hpxA6aJ0f8Id/BnU7XSatgPleS4p0L7ZbO9UMJhnZV/fVYLMHDIA6CQpD0CnZ3mECyDXLQz05YL3XT/lWd71fRXK2ejr7jsGufsLfirbhxdjqDZu07C5uJDBw8roz7hkqksAZKS99Us4pDBE2qizlXVLZbBN0SNYNUTbkLKTy+lHamT+wTXPnb78Fl/nC8GAQ+cFCQ8y3xjfs0S6+Xbvr57ctqKr/QvNFEv4uYnn7IQTEpv7y6YX//P5w3GP6+x9ppCfwqW2CrkvUzVjnugCLtPQ6graaULg3JWsZgayQDoBEuG4Bp3M0tYlsHTa+QKBgQDqczjN0/LHeE2RtBZCDRE+2CByrX3eHMThfSxGcUD6aee+jP+S2OUjgjMFoqEbXz3/ZhU1rYCTjDsp8wgL27Lh2TYf7Rm9LHC1YIeixh8oNWpo1Bt5UWeFXBRTwNuiJUDx9ZOBygQ5f6hiL2Dnru0pVIh3H1OR7LuSWehmOaa7NQKBgQCbX7qjJRDENdjds0qWgM5YUtNiAa7t6bhq1n3UUf3Gy4SEIpEs5P0L3urdvrxFv/BdakIox1/1ze3y+36TwTjJuli1j5Bn+X8TMPKmXhpZTzYg3iLZU6ufmcJizQtrJGW7qfF/xN+FEaacO16xxIhTn55fX6JlQ3wRc0crq95HKwKBgDk3aXOB+EwJ5hRa+NuhyMWnhTO3d3JPXxUQsU93sD3svqvYST8TQ8iIq98CM4M0mTLNPPvenfRkUsQIFbyfH2bS1cyw1ok+YTtClZd59nyfnJp8uT/ASB1ZvXQ7Kt7FbLYgEqGoJaPKrdNYcLPaEvL1OGCp+oEwXw52dqsMAs7JAoGANg+Z7fgQnGSr/3/JvRI2Oc8f06MITambzDizcXPR3CCmDB/G6ZsHXOEEUYFzGsXNCYPWXz/36JvtZjURdrGtY6teAFZihXrvNys50p89hcOk7sy7zWhqd87VLvFvPqlcaG6aI73JlBBvKz8RFMNwN8B7J24sIBXaDmxQ4CYd4h8CgYB4jsYgvI7i16aDr3YpiapvIIoALEU8W9V0+TgyowBzDmTQW4rKCSQ26bgdFTWZH3lGVpAoOt5XQvpkPCstZErCjdzBwV97ek9buuKY9ea7Ww7ICQSSusiN8Oyjp4Rf1RmnsAU5osS6YCH9u/UC5fgfQVOM3sSlEdsG2CBYMBk19w=="
  alipay-public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApcNgbnwGS3gDGv9ohSJaykXmJvfq1m0xrlawaJf5oJaYFC5lkGyYaNG115XBInt+NDL8HnBXdMiHs5PfSZXcSW0zmEF1/pf/d3nwdGr5z+NMRND1eRwKJ+LhB/eZMqaS2CeswQxh83etI+72i3TwFsrfNcE2ylWDvBfl1g9VZ/yCcRbpPejEcdok2cx7bcqQwRs18OrGeL1ix+R9DKLYtOIiJlzAZpGsqUSNlZgN2rT62ZQmjKCH/vzF1DLgqV8s20sT0Xx1h4YPDPNoAH0wgxExcOQbuZsc3EIiJhfVlhnQXgxlu+ZIC+2oOBqvf3XlarEagq/PSt9iacjcGzpprQIDAQAB"
  gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  sign-type: RSA2
  charset: utf-8
  format: json
  return-url: http://localhost:9103/order/alipay/return
  notify-url: http://localhost:9103/order/alipay/notify
  seller-id: 2088721028872203

# --- Logging (Keep as before) ---
logging:
  level:
    com.example.order: INFO
    org.springframework.cloud.stream: INFO
    org.apache.rocketmq: WARN
    # Add ShardingSphere logging if needed for debugging
    org.apache.shardingsphere: INFO # or DEBUG
    com.alipay.api: INFO