
# src/main/resources/application.yml
server:
  port: 9100

spring:

  codec:
    max-in-memory-size: 10MB
  webflux:   # 或更大
    multipart:
      max-in-memory-size: 10MB
      max-part-size: 50MB      #   单个 part 的大小
      max-request-size: 10MB   #   整个表单的大小（2.7.0 以后可省略）

  cloud:
    gateway:
      httpclient:
        max-in-memory-size: 10MB
      default-filters: # ❹ 如果还想做兜底保护，可以再加一个 RequestSize 过滤器
        - name: RequestSize
          args:
            maxSize: 52428800   # 50 * 1024 * 1024
      routes:
        - id: auth-service
          uri: lb://knowledge-planet-auth
          predicates:
            - Path=/api/auth/**, /api/user/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: article-service
          uri: lb://knowledge-planet-article
          predicates:
            - Path=/api/article/**, /api/planet/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                key-resolver: "#{@ipKeyResolver}"

        - id: order-service
          uri: lb://knowledge-planet-order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # 全局 CORS 配置
      globalcors:
        cors-configurations:
          # 对所有路径生效
          '[/**]':
            allowedOrigins: "http://localhost:5173"   # 前端地址
            allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 1800
  redis:
    host: localhost
    port: 6379

# 白名单路径
whitelist:
  urls: /api/auth/login,/api/auth/register,/api/planet/list