
# src/main/resources/application.yml
server:
  port: 9100

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://knowledge-planet-auth
          predicates:
            - Path=/api/auth/**, /api/user/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: article-service
          uri: lb://knowledge-planet-article
          predicates:
            - Path=/api/article/**, /api/planet/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                key-resolver: "#{@ipKeyResolver}"

        - id: order-service
          uri: lb://knowledge-planet-order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # 全局 CORS 配置
      globalcors:
        cors-configurations:
          # 对所有路径生效
          '[/**]':
            allowedOrigins: "http://localhost:5173"   # 前端地址
            allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 1800
  redis:
    host: localhost
    port: 6379

# 白名单路径
whitelist:
  urls: /api/auth/login,/api/auth/register,/api/planet/list