# src/main/resources/application.yml
server:
  port: 9100

spring:
  # Keep existing codec/webflux settings
  codec:
    max-in-memory-size: 10MB
  webflux:
    multipart:
      max-in-memory-size: 10MB
      max-part-size: 50MB
      max-request-size: 10MB

  cloud:
    gateway:
      # Keep existing httpclient/default-filters settings
      httpclient:
        max-in-memory-size: 10MB
      default-filters:
        - name: RequestSize
          args:
            maxSize: 52428800

      routes:
        - id: auth-service
          uri: lb://knowledge-planet-auth
          predicates:
            - Path=/api/auth/**, /api/user/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter # Keep existing filters
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: article-service
          uri: lb://knowledge-planet-article
          # Update path if /api/planet/** is no longer used
          predicates:
            - Path=/api/article/** # Removed /api/planet/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter # Keep existing filters
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                key-resolver: "#{@ipKeyResolver}"

        # *** ADDED: Route for Order Service ***
        - id: order-service
          uri: lb://knowledge-planet-order # Route to the new order service
          predicates:
            - Path=/api/order/** # Define path prefix for order APIs
          filters:
            - StripPrefix=1 # Remove /api prefix before forwarding
            - name: RequestRateLimiter # Apply rate limiting
              args:
                redis-rate-limiter.replenishRate: 10 # Adjust rates as needed
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # Keep existing globalcors settings
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 1800

  # Keep existing redis settings
  redis:
    host: localhost
    port: 6379

# Keep existing whitelist settings (adjust if needed)
whitelist:
  urls: /api/auth/login,/api/auth/register,/api/article/list # Example: /api/planet/list removed

# Ensure bootstrap.yml is correctly configured for Nacos